### ISSUE TITLE
S3 bucket is not accessible

### ISSUE THREAD

**Issue by geoaxis** [aws-samples/msk-powered-financial-data-feed#6]
While it is possible to use https://aws-blogs-artifacts-public.s3.amazonaws.com/BDB-3696/dataFeedMskArtifacts.zip

to download artifacts, the same can be done using `aws s3 cp`

There are missing instructions on how to update properties to use the bucket created via the CF template of the project.

**Comment by soadiego** [comment]
Fixed with new code.
